---
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/left_camera/image"
  gz_topic_name: "/left_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/center_camera/image"
  gz_topic_name: "/center_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/center_camera/depth_image"
  gz_topic_name: "/center_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/right_camera/image"
  gz_topic_name: "/right_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/left_camera/camera_info"
  gz_topic_name: "/left_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/center_camera/camera_info"
  gz_topic_name: "/center_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/right_camera/camera_info"
  gz_topic_name: "/right_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/aic/gazebo/contacts/off_limit"
  gz_topic_name: "/aic/gazebo/contacts/off_limit"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/scoring/tf"
  gz_topic_name: "/cable_0/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/scoring/tf"
  gz_topic_name: "/cable_1/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/scoring/tf"
  gz_topic_name: "/cable_2/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/scoring/tf"
  gz_topic_name: "/cable_3/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/scoring/tf"
  gz_topic_name: "/cable_4/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/scoring/tf"
  gz_topic_name: "/task_board/pose_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/scoring/insertion_event"
  gz_topic_name: "/cable_0/insertion_event"
  ros_type_name: "std_msgs/msg/String"
  gz_type_name: "gz.msgs.StringMsg"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/scoring/insertion_event"
  gz_topic_name: "/cable_1/insertion_event"
  ros_type_name: "std_msgs/msg/String"
  gz_type_name: "gz.msgs.StringMsg"
  direction: GZ_TO_ROS
  lazy: true
