[workspace]
name = "aic"
authors = ["Teo Koon Peng <koonpeng@intrinsic.ai>"]
channels = ["robostack-kilted", "conda-forge"]
platforms = ["linux-64", "osx-arm64", "linux-aarch64"]
version = "0.1.0"
conda-pypi-map = { "robostack-kilted" = "robostack_mapping.json" }
preview = ["pixi-build"]

[target.linux-64.dependencies]
evdev = ">=1.9.2,<2"

[dependencies]
isort = "==5.13.2"                                                                     # version bundled by the vscode extension
json5 = ">=0.13.0,<0.14"                                                               # version bundled by the vscode extension
numpy = "<2.3.0"
packaging = ">=24.2,<26.0"                                                             # required by lerobot==0.4.3
pyright = "==1.1.408"
ros-kilted-aic-control-interfaces = { path = "aic_interfaces/aic_control_interfaces" }
ros-kilted-aic-example-policies = { path = "aic_example_policies" }
ros-kilted-aic-model = { path = "aic_model" }
ros-kilted-aic-model-interfaces = { path = "aic_interfaces/aic_model_interfaces" }
ros-kilted-aic-task-interfaces = { path = "aic_interfaces/aic_task_interfaces" }
ros-kilted-aic-teleoperation = { path = "aic_utils/aic_teleoperation" }
ros-kilted-aic-training-interfaces = { path = "aic_utils/aic_training_interfaces" }
ros-kilted-control-msgs = "*"                                                          # lerobot_robot_ros
ros-kilted-geometry-msgs = "*"                                                         # lerobot_robot_ros
ros-kilted-lerobot-robot-aic = { path = "aic_utils/lerobot_robot_aic" }
ros-kilted-moveit-msgs = "*"                                                           # lerobot_robot_ros
ros-kilted-rclpy = "*"
ros-kilted-rmw-zenoh-cpp = "*"
ros-kilted-ros-core = "*"
ros-kilted-sensor-msgs = "*"                                                           # lerobot_robot_ros
ros-kilted-std-msgs = "*"                                                              # lerobot_robot_ros
ros-kilted-std-srvs = "*"
ros-kilted-tf2-ros-py = "*"
setuptools = ">=71.0.0,<81.0.0"                                                        # required by lerobot==0.4.3

[pypi-dependencies]
huggingface-hub = { version = "~=1.7" }
lerobot = "==0.5.1"
lerobot_robot_ros = { git = "https://github.com/koonpeng/lerobot-ros", rev = "87708d0ae14a724bca78f8ae9d55448332509a57", subdirectory = "lerobot_robot_ros" }
lerobot_teleoperator_devices = { git = "https://github.com/koonpeng/lerobot-ros", rev = "87708d0ae14a724bca78f8ae9d55448332509a57", subdirectory = "lerobot_teleoperator_devices" }
mujoco = "==3.5.0"
pynput = ">=1.7.6,<2"
pyspacemouse = ">=2.0.0, <3"

[activation]
scripts = ["pixi_env_setup.sh"]
