/*
 * Copyright (C) 2025 Intrinsic Innovation LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef AIC_CONTROLLER__AIC_CONTROLLER_HPP_
#define AIC_CONTROLLER__AIC_CONTROLLER_HPP_

#include <memory>
#include <optional>
#include <string>

#include "aic_controller/actions/cartesian_impedance_action.hpp"
#include "aic_controller/actions/gravity_compensation_action.hpp"
#include "aic_controller/actions/joint_impedance_action.hpp"
#include "aic_controller/cartesian_limits.hpp"
#include "aic_controller/cartesian_state.hpp"
#include "aic_controller/joint_state.hpp"
#include "aic_controller/utils.hpp"
#include "controller_interface/controller_interface.hpp"
#include "joint_limits/joint_limits.hpp"
#include "joint_limits/joint_limits_urdf.hpp"
#include "kinematics_interface/kinematics_interface.hpp"
#include "pluginlib/class_loader.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_publisher.hpp"
#include "realtime_tools/realtime_thread_safe_box.hpp"
#include "semantic_components/force_torque_sensor.hpp"
#include "tf2_eigen/tf2_eigen.hpp"

// The versions conditioning is added here to support the
// source-compatibility with ROS 2 Jazzy
#include "rclcpp/version.h"
#if RCLCPP_VERSION_GTE(29, 0, 0)
#include "urdf/model.hpp"
#elif
#include "urdf/model.h"
#endif

// Interfaces
#include "aic_control_interfaces/msg/controller_state.hpp"
#include "aic_control_interfaces/msg/joint_motion_update.hpp"
#include "aic_control_interfaces/msg/motion_update.hpp"
#include "aic_control_interfaces/msg/target_mode.hpp"
#include "aic_control_interfaces/msg/trajectory_generation_mode.hpp"
#include "aic_control_interfaces/srv/change_target_mode.hpp"
#include "lifecycle_msgs/msg/state.hpp"
#include "std_srvs/srv/trigger.hpp"
#include "trajectory_msgs/msg/joint_trajectory_point.hpp"

// Auto-generated by generate_parameter_library
#include "aic_controller/aic_controller_parameters.hpp"
#include "hardware_interface/types/hardware_interface_type_values.hpp"

//==============================================================================
namespace aic_controller {

using MotionUpdate = aic_control_interfaces::msg::MotionUpdate;
using JointMotionUpdate = aic_control_interfaces::msg::JointMotionUpdate;
using ChangeTargetMode = aic_control_interfaces::srv::ChangeTargetMode;
using TargetMode = aic_control_interfaces::msg::TargetMode;
using TrajectoryGenerationMode =
    aic_control_interfaces::msg::TrajectoryGenerationMode;
using JointTrajectoryPoint = trajectory_msgs::msg::JointTrajectoryPoint;
using ControllerState = aic_control_interfaces::msg::ControllerState;
using JointLimits = joint_limits::JointLimits;

//==============================================================================
enum class ControlMode : uint8_t { Invalid = 0, Admittance = 1, Impedance = 2 };

//==============================================================================
/**
 * The AIC Controller subscribes to user commands at a lower frequency and
 * based on the control mode:
 * 1. Admittance mode: Outputs interpolated user commands at
 * a higher frequency to the admittance controller.
 * 2. Impedance mode: Outputs control commands to the robot arm's hardware
 * interface from an internal impedance controller implementation.
 */
class Controller : public controller_interface::ControllerInterface {
 public:
  Controller();

  /**
   * @copydoc
   * controller_interface::ControllerInterface::command_interface_configuration()
   */
  controller_interface::InterfaceConfiguration command_interface_configuration()
      const override;

  /**
   * @copydoc
   * controller_interface::ControllerInterface::state_interface_configuration()
   */
  controller_interface::InterfaceConfiguration state_interface_configuration()
      const override;

  /**
   * @copydoc controller_interface::ControllerInterface::on_init()
   */
  controller_interface::CallbackReturn on_init() override;

  /**
   * @copydoc controller_interface::ControllerInterface::on_configure()
   */
  controller_interface::CallbackReturn on_configure(
      const rclcpp_lifecycle::State& previous_state) override;

  /**
   * @copydoc controller_interface::ControllerInterface::on_activate()
   */
  controller_interface::CallbackReturn on_activate(
      const rclcpp_lifecycle::State& previous_state) override;

  /**
   * @copydoc controller_interface::ControllerInterface::on_deactivate()
   */
  controller_interface::CallbackReturn on_deactivate(
      const rclcpp_lifecycle::State& previous_state) override;

  /**
   * @copydoc controller_interface::ControllerInterface::on_cleanup()
   */
  controller_interface::CallbackReturn on_cleanup(
      const rclcpp_lifecycle::State& previous_state) override;

  /**
   * @copydoc controller_interface::ControllerInterface::update()
   */
  controller_interface::return_type update(
      const rclcpp::Time& time, const rclcpp::Duration& period) override;

 private:
  /**
   * @brief Update fields of state_current with joint states from hardware
   * interfaces
   *
   * @param state_current Sensed joint states
   */
  void read_state_from_hardware(
      JointTrajectoryPoint& state_current, CartesianState& tool_state_current,
      Eigen::Matrix<double, 6, 1>& sensed_wrench_at_tip);

  /**
   * @brief Write values from state_command to claimed command interfaces
   *
   * @param state_command Commanded joint states
   */
  void write_state_to_hardware(const JointTrajectoryPoint& state_command);

  /**
   * @brief Populate the cartesian translation, velocity and rotation limits
   * from user-defined parameters
   *
   * @param cartesian_limits CartesianLimits class to be populated
   * @param params parameters
   * @return true
   * @return false
   */
  bool populate_cartesian_limits(const aic_controller::Params& params,
                                 CartesianLimits& cartesian_limits);

  /**
   * @brief Populate the controller state message with the computed cartesian
   * and joint commands.
   *
   * @param controller_state Controller state message to be populated
   */
  void populate_controller_state(ControllerState& controller_state);

  /**
   * @brief For Cartesian targets, clamp the target_state to given limits
   *
   * @param limits Provided Cartesian Limits to be clamped to
   * @param mode Trajectory generation mode
   * @param target_state target state to be clamped
   * @param soft_margin_meters Safety margin for position
   * @param soft_margin_radians Safety margin for rotation
   * @return true Successfully clamped target_state
   * @return false Failed to clamp target_state
   */
  bool clamp_reference_to_limits(const CartesianLimits& limits,
                                 const uint8_t& mode,
                                 CartesianState& target_state,
                                 double soft_margin_meters = 0.0,
                                 double soft_margin_radians = 0.0);

  /**
   * @brief For joint targets, clamp the target_state to given limits
   *
   * @param limits Provided Joint Limits to be clamped to
   * @param mode Trajectory generation mode
   * @param target_state target state to be clamped
   * @param soft_margin_radians Safety margin for joint positions
   * @return true Successfully clamped target_state
   * @return false Failed to clamp target_state
   */
  bool clamp_joint_reference_to_limits(const std::vector<JointLimits>& limits,
                                       const uint8_t& mode,
                                       JointState& target_state,
                                       double soft_margin_radians = 0.0);

  /**
   * @brief For Cartesian targets, linearly interpolate the last_reference to
   * the target_state to compute new_reference
   *
   * @param last_reference Starting state
   * @param target_state Final state
   * @param remaining_time_to_target_seconds Remaining time to reach the target
   * @param control_frequency Frequency of control loop in Hz
   * @param mode Trajectory generation mode
   * @param new_reference Interpolated reference
   * @return true Successfully computed new reference
   * @return false Failed to compute new reference
   */
  bool update_reference_linear_interpolation(
      const CartesianState& last_reference, const CartesianState& target_state,
      const double remaining_time_to_target_seconds,
      const double control_frequency, const uint8_t& mode,
      CartesianState& new_reference);

  /**
   * @brief For joint targets, linearly interpolate the last_reference to
   * the target_state to compute new_reference
   *
   * @param last_reference Starting state
   * @param target_state Final state
   * @param remaining_time_to_target_seconds Remaining time to reach the target
   * @param control_frequency Frequency of control loop in Hz
   * @param mode Trajectory generation mode
   * @param new_reference Interpolated reference
   * @return true Successfully computed new reference
   * @return false Failed to compute new reference
   */
  bool update_joint_reference_linear_interpolation(
      const JointState& last_reference, const JointState& target_state,
      const double remaining_time_to_target_seconds,
      const double control_frequency, const uint8_t& mode,
      JointState& new_reference);

  /**
   * @brief Interpolate the parameters for the impedance control parameters and
   * the feedforward wrench at the tip.
   * Based on the current target_mode, it will interpolate either the joint
   * impedance parameters or the Cartesian impedance parameters.
   *
   */
  void interpolate_impedance_parameters();

  // controller parameters
  std::shared_ptr<aic_controller::ParamListener> param_listener_;
  aic_controller::Params params_;

  std::size_t num_joints_;

  ControlMode control_mode_;
  uint8_t target_mode_value_;

  CartesianLimits cartesian_limits_;
  std::vector<JointLimits> joint_limits_;

  // Impedance controller for cartesian targets
  std::unique_ptr<CartesianImpedanceAction> cartesian_impedance_action_;
  CartesianImpedanceParameters impedance_params_;
  // Feedforward wrench in TCP frame
  Eigen::Matrix<double, 6, 1> feedforward_wrench_at_tip_;
  // Current wrench sensed from force torque sensor in TCP frame
  Eigen::Matrix<double, 6, 1> sensed_wrench_at_tip_;
  // Tare offset for force torque sensor in base_link frame, this value is fixed
  // upon calibration
  Eigen::Matrix<double, 6, 1> tare_offset_at_base_;
  // Tare offset for force torque sensor in TCP frame, to be updated on each
  // control loop iteration
  Eigen::Matrix<double, 6, 1> tare_offset_at_tip_;

  // Impedance controller for joint targets
  std::unique_ptr<JointImpedanceAction> joint_impedance_action_;
  JointImpedanceParameters joint_impedance_params_;

  // Gravity Compensation action
  std::unique_ptr<GravityCompensationAction> gravity_compensation_action_;

  // ROS2 subscribers for user commands
  rclcpp::Subscription<MotionUpdate>::SharedPtr motion_update_sub_;
  rclcpp::Subscription<JointMotionUpdate>::SharedPtr joint_motion_update_sub_;

  // ROS2 Service servers for updating controller states
  rclcpp::Service<ChangeTargetMode>::SharedPtr change_target_mode_srv_;
  rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr
      tare_force_torque_sensor_srv_;

  // Real-time publisher for controller state
  rclcpp::Publisher<ControllerState>::SharedPtr state_publisher_;
  std::unique_ptr<realtime_tools::RealtimePublisher<ControllerState>>
      state_publisher_rt_;
  ControllerState state_msg_;

  // Real-time boxes for thread-safe access
  realtime_tools::RealtimeThreadSafeBox<MotionUpdate> motion_update_rt_;
  MotionUpdate motion_update_;
  realtime_tools::RealtimeThreadSafeBox<JointMotionUpdate>
      joint_motion_update_rt_;
  JointMotionUpdate joint_motion_update_;

  std::atomic<bool> motion_update_received_;

  // Last value written to controller interfaces
  std::optional<JointTrajectoryPoint> last_commanded_state_;
  // Desired target state read from MotionUpdate user commands
  std::optional<CartesianState> target_state_;
  // Desired target state read from JointMotionUpdate user commands
  std::optional<JointState> joint_target_state_;
  // Latest joint states read from hardware interface
  JointTrajectoryPoint current_state_;
  // Latest cartesian state of tool calculatd via forward kinematics from
  // joint position values in current_state_
  CartesianState current_tool_state_;
  // Reference used for interpolation
  // todo(johntgz) Investigate if we can replace last_tool_reference_ with
  // current_tool_state_
  CartesianState last_tool_reference_;
  // Joint reference used for interpolation
  JointState last_joint_reference_;
  // The last computed error between the current and target tool pose
  Eigen::Matrix<double, 6, 1> last_tool_pose_error_;

  double time_to_target_seconds_;
  double remaining_time_to_target_seconds_;

  // Time since last non-negligible change in error
  rclcpp::Time last_error_change_time_;

  std::shared_ptr<
      pluginlib::ClassLoader<kinematics_interface::KinematicsInterface>>
      kinematics_loader_;
  std::unique_ptr<kinematics_interface::KinematicsInterface> kinematics_;

  // force torque sensor
  std::unique_ptr<semantic_components::ForceTorqueSensor> force_torque_sensor_;
};

}  // namespace aic_controller

#endif  // AIC_CONTROLLER__AIC_CONTROLLER_HPP_
