name: aic
services:
  eval:
    image: ghcr.io/intrinsic-dev/aic/aic_eval
    # image: my-eval:v1
    build:
      dockerfile: docker/aic_eval/Dockerfile
      context: ..
    command: gazebo_gui:=false launch_rviz:=false ground_truth:=false start_aic_engine:=true shutdown_on_aic_engine_exit:=true model_discovery_timeout_seconds:=600
    gpus: all
    networks:
      - default
    environment:
      AIC_EVAL_PASSWD: CHANGE_IN_PROD
      AIC_MODEL_PASSWD: CHANGE_IN_PROD
      # AIC_ENABLE_ACL: true
  model:
    image: my-solution:v1
    build:
      dockerfile: docker/aic_model/Dockerfile
      context: ..
    gpus: all
    networks:
      - default
    environment:
      RMW_IMPLEMENTATION: rmw_zenoh_cpp
      ZENOH_ROUTER_CHECK_ATTEMPTS: -1
      AIC_ROUTER_ADDR: eval:7447
      AIC_MODEL_PASSWD: CHANGE_IN_PROD
      # AIC_ENABLE_ACL: true
networks:
  default:
    internal: true
