---
# Tier2 scoring configuration.

# List of topics to subscribe.
topics:
  - topic:
      name: "/joint_states"
      type: "sensor_msgs/msg/JointState"
  - topic:
      name: "/scoring/tf"
      type: "tf2_msgs/msg/TFMessage"
  - topic:
      name: "/scoring/tf_static"
      type: "tf2_msgs/msg/TFMessage"
  - topic:
      name: "/aic/gazebo/contacts/off_limit"
      type: "ros_gz_interfaces/msg/Contacts"
  - topic:
      name: "/fts_broadcaster/wrench"
      type: "geometry_msgs/msg/WrenchStamped"

# List of entity pairs to monitor.
plugs:
  - plug:
      name: "sfp_cable::plug_a"
      type: "sfp"
  - plug:
      name: "sfp_cable::plug_b"
      type: "sfp"
  - plug:
      name: "other_cable::plug_c"
      type: "other"
  - plug:
      name: "other_cable::plug_d"
      type: "other"
  - plug:
      name: "other_cable::plug_d"
      type: "other"

ports:
  - port:
      name: "sfp_module"
      type: "sfp"
  - port:
      name: "sfp_module"
      type: "sfp"
  - port:
      name: "other_sfp_module"
      type: "sfp"
